### ISSUE TITLE
Update stored emails

### ISSUE THREAD

**Issue by davidhennemann** [hpi-swa-teaching/IMAPClient#100]
If a Mail is loaded into storage, and some other client changes flags on these mails...our mail client wont update his flags. We need to figure out a smart way, how to reflect changes on the server into our already loaded mails.

"In that case pressing update will load the locally stored email. And the locally stored email does not know about any changes on the other device. For similar reason I initially never stored and loaded the flags locally, but always loaded from the server (thus, there was never a reason to store them). But this caused bad performance, so I changed it in this issue again..."

**Comment by mariwalt** [comment]
There is actually an easy way to solve this issue. In case of an email that is loaded from your local disk, we will nevertheless retrieve the flags from the server. But everything else (body, subject etc.) is still loaded from the local file, thus, performance should be fine.
This works fine for the update after your first login (I tested it). But after the first login, pressing the update button will only load those emails that are new on the server and not yet listed in UI. So any changes to emails listed in the UI will be ignored. Maybe we should reconsider the logic of "Update" (and reverse some changes done in fixing_leonard?). Leonard, what do you think?

**Comment by davidhennemann** [comment]
Should be closes with #155
