### ISSUE TITLE
Load all Mails

### ISSUE THREAD

**Issue by davidhennemann** [hpi-swa-teaching/IMAPClient#114]
For display correct number of unread emails, its necassary to fetch all mails. 

- [ ]  Load all mails from server
- [ ] Add a loading animation for this (its not a good to be unresponsible for ages without loading animation)
- [ ]  Figure out a smart mechanism for update flags and load new mails.

Depends on #108.

**Comment by davidhennemann** [comment]
Small Update: We implemented #110, but it contained a few bugs so we first should fix that: #133.

**Comment by davidhennemann** [comment]
We decided to not load all mails for the moment, because retriving 1000+ mails was very slow. :D

**Comment by EightSQ** [comment]
What about users with gigabytes of mails in their inbox? As we will store them in the image prospectively, we decided that this feature is not to be considered anymore.
