### ISSUE TITLE
Scrollbars not working after support of multiple email accounts

### ISSUE THREAD

**Issue by davidhennemann** [hpi-swa-teaching/IMAPClient#116]
Somehow the horizontal scrollbar is small while no folder is selected, but after selecting a folder, its just expanding to full size.

![image](https://user-images.githubusercontent.com/6185006/41556176-3d69e7b6-733a-11e8-9f22-c6f992f70698.png)

**Comment by felixrindt** [comment]
Can still reproduce this by just opening the application

**Comment by JuliaJoch** [comment]
this seems to be fixed already as we could not reproduce it in the newest version
