### ISSUE TITLE
Fix horizontal scroll bar in e-mail window

### ISSUE THREAD

**Issue by ClayGee** [hpi-swa-teaching/IMAPClient#123]
Als User möchte ich nach links und rechts schrollen können im E-Mail Fenster.

**Comment by ClayGee** [comment]
As it turns out it is really difficult to find the culprit of this problem. After investing some time in it I decided it isn't worth it and that I need to find a different solution. It may not be the most elegant solution, but I don't think it causes any problems. So the window opens with the perfect width, so that all information is visible. I decided to make the scrollbar obsolete by preventing to resize the window horizontally beyond this point.

**Comment by EightSQ** [comment]
Maybe we should close this, as it seems to be fixed with #141.

**Comment by EightSQ** [comment]
Text is already wrapped, so this is not an issue anymore.
