### ISSUE TITLE
Fix code that emphasizes unread e-mails

### ISSUE THREAD

**Issue by ClayGee** [hpi-swa-teaching/IMAPClient#124]

**Comment by davidhennemann** [comment]
I will fix this by writing a script, which removes the instance of `ICLoadOlderEmail` + Removes the old mail folders. The Bug Appeared because of invalid `ICLoadOlderEmail`-instances.

**Comment by davidhennemann** [comment]
Should be fixed with: ab9d24d8bb9291430f216d3ad67def7c3588a9ab
