### ISSUE TITLE
Make windows appear at the same position

### ISSUE THREAD

**Issue by ClayGee** [hpi-swa-teaching/IMAPClient#129]
Right now windows (especialy the login windows) "spawn" all over the place

**Comment by davidhennemann** [comment]
I can't find any suitable solution. Seems like Tool Builder, wont let us do that...

**Comment by felixrindt** [comment]
"As a user, I want Login and email windows to appear at a consistent location, so I don't have to search for the window when it opens."

**Comment by Paulpanther** [comment]
This is a squeak setting and can be set by the user
