### ISSUE TITLE
Fix the useraccounts window, so that the imap window scales dynamically if it is being resized

### ISSUE THREAD

**Issue by ClayGee** [hpi-swa-teaching/IMAPClient#131]
![capture](https://user-images.githubusercontent.com/29133220/41719192-9c9e568c-755f-11e8-8d24-e59041a036d5.PNG)

**Comment by felixrindt** [comment]
"Me as a user, I'd like to move the seperator between the account and folder list, so I can adjust the height of the lists to see as much information at once as possible."
