### ISSUE TITLE
Offline Modus

### ISSUE THREAD

**Issue by ClayGee** [hpi-swa-teaching/IMAPClient#139]
As a user I would like to have an offline mode in order to be able to access mails that have been previously loaded even when there's no internet connection.

**Comment by martintaraz** [comment]
We should consider where we want to persist the mails and ask the user before

**Comment by felixrindt** [comment]
@martintaraz Can you please explain what has been done to ease the implementation of an offline mode in the future?

**Comment by JuliaJoch** [comment]
related to #348 
once that one is solved, emails can be persisted as maildir objects on disc.
