### ISSUE TITLE
ICEndpoint>>loggedIn and ICEndpoint>>isLoggedIn redundant?

### ISSUE THREAD

**Issue by querenker** [hpi-swa-teaching/IMAPClient#15]
If I understand the command in Slack correctly the getter for a boolean variable should be named in the form is{instancevariable}. Is it then necessary to have an other getter?

**Comment by Johannes-Schneider** [comment]
In SWA we learned, that we should use another method to access boolean members (named "is{NameOfMember}") in addition to its (auto generated) getter
This is to add more semantics to the code when accessing these members (of cause you could just use the generated getter, but it wouldnt sound as nice)
