### ISSUE TITLE
MessageNotUnderstood error after login

### ISSUE THREAD

**Issue by davidhennemann** [hpi-swa-teaching/IMAPClient#158]
Sometimes after logging in this error appears:

![image](https://user-images.githubusercontent.com/6185006/43189388-c162a296-8ff6-11e8-8801-02c69e61c69a.png)

I dont know where it comes from, and you just can close it, but its irritating. It opens after logging in with keyboard shortcut ...

**Comment by felixrindt** [comment]
Cannot reproduce this on our SWE image.
