### ISSUE TITLE
Implement test cases for ICFolder class

### ISSUE THREAD

**Issue by Johannes-Schneider** [hpi-swa-teaching/IMAPClient#16]
Within my latest commit we implemented our new class `ICFolder`.
We need to find some useful ways to test this new class.

I already wrote a test scenario when adding new folders in the hierarchy.

**Comment by julianweise** [comment]
Implemented further tests -> see branch.
Did not implemented tests for Transcript output. From my point of view this makes no sense.
But we can discuss this tomorrow.
