### ISSUE TITLE
Move operation sometimes fails

### ISSUE THREAD

**Issue by EightSQ** [hpi-swa-teaching/IMAPClient#167]
Sometimes moving an email throws an 'Wrong username & password' notification and blocks the main thread, until after approximately 30 seconds a ConnectionTimedOut error is thrown. Maybe the connection could be moved to another Thread in order to not block the entire Image.

![Screenshot 2019-04-23 at 18 15 37](https://user-images.githubusercontent.com/1622854/56598104-1e857880-65f4-11e9-8f34-d0672cf3357b.png)

Maybe this could be fixed together with #29.

**Comment by JuliaJoch** [comment]
This failure never got visible during this years iteration and we could not reproduce it. We are closing the issue for now. In case it comes up again, please let us know.
