### ISSUE TITLE
"load older eMails" should look like a button

### ISSUE THREAD

**Issue by Paulpanther** [hpi-swa-teaching/IMAPClient#168]
Currently the button looks like a mail, which is missleading

![DeepinScreenshot_select-area_20190423182029](https://user-images.githubusercontent.com/23553744/56598336-d8c0b400-65e3-11e9-8cb2-23f3f694b77d.png)

**Comment by Paulpanther** [comment]
Alternative: Remove Button and load on scroll down (Suggested by client)

**Comment by Paulpanther** [comment]
![squeak](https://user-images.githubusercontent.com/23553744/57216290-fd069280-6fde-11e9-9664-01d1bb2cf925.png)
So siehts momentan aus

**Comment by EightSQ** [comment]
Closed for now. We will implement the centralisation and capitalisation of the string.
