### ISSUE TITLE
Response class?

### ISSUE THREAD

**Issue by querenker** [hpi-swa-teaching/IMAPClient#17]
ICEndpoint owns methods to check the responses. These could also be used by other objects. Maybe it is a good idea to encapsulate these in a Response class?

**Comment by Johannes-Schneider** [comment]
Which methods do you mean exactly?
Is this question about ICEndpoint >> checkForBadResponse (for example)?
And which other classes could use these methods? Could you give me an example please?

**Comment by querenker** [comment]
Currently the ICMockServer have to check if a command succeeded to perform a transition into a new state (ICMockSever>>makeTransition: withResponse:). Some commands can only be performed into a specific state, for example a fetch command is only possible in "selected". This is mocked through different response dictionaries for every state. Some commands like "select" and "login" change the state, but only if the command was successful. At the moment ICMockServer has a message "commandSucceeded" which uses the class variable from ICEndpoint.
