### ISSUE TITLE
Enhance emphasis of 'load older emails' button

### ISSUE THREAD

**Issue by EightSQ** [hpi-swa-teaching/IMAPClient#182]
We want the Load Older Emails button string to begin uppercase.
We want it to be in the very center of the list item line.

This is a follow-up on #176.

**Comment by Paulpanther** [comment]
This turns out to be hard. The problem is that somehow the "Load Older Email" Button isn't used in the calculations for the column size

**Comment by Paulpanther** [comment]
I'm removing it from the milestone

**Comment by felixrindt** [comment]
Can this be closed @Paulpanther (esp because there is #187 )
