### ISSUE TITLE
Make coveralls measure only Core package

### ISSUE THREAD

**Issue by EightSQ** [hpi-swa-teaching/IMAPClient#183]
We could [configure coverage measurement ](https://github.com/hpi-swa-teaching/IMAPClient/blob/dcb0c90993e48c4cd79ea43f981e3a98abfff0b9/.smalltalk.ston#L12) so that only the coverage of the _Core package_ is actually measured, since we are not yet planning to conduct UI testing [1] and coverage of the _Tests package_ itself [2] I think is unneccessary.

I think you have more experience with this stuff, @martintaraz...?

[1] Coverage of the UI Package currently is at 0%.
[2] Coverage of the Tests Package is at 97%.

**Comment by martintaraz** [comment]
Changing this to only the core package seems like a good Idea to me.
I have some experience with coverage reporter configuration (not coveralls specifically) and will work on this next Sprint

**Comment by EightSQ** [comment]
This has been taken care of in #188.
