### ISSUE TITLE
ICEmail defaultSubject

### ISSUE THREAD

**Issue by timgarrels** [hpi-swa-teaching/IMAPClient#196]
ICEmail implements a defaultSubject method. This is used if the subject header field is just an empty string.
This functionality is used for the UI, that the user does at least see "No subject" in the mail line.

I think this is a UI functionality and ICEmail is not the place to do human readability conversion or beautify processes.
I suggest that the defaultSubject constant is moved to IMAP-UI and the subject replacement "empty String" -> defaultSubject is handled there as well.

**Comment by Paulpanther** [comment]
a
