### ISSUE TITLE
"as yet unclassified" - Category

### ISSUE THREAD

**Issue by timgarrels** [hpi-swa-teaching/IMAPClient#207]
There are some occurrences of unclassified methods in our code. The refactor would consist of finding these methods, sorting them into fitting existing categories or creating new fitting categories if necessary

**Comment by Paulpanther** [comment]
**Occurrences:** `ICEndPoint`, `ICHelper` (Class methods), `ICLoginDialog`, `ICPasswordDialog`, `ICAuthenticationInfoTest` (Instance and Class methods), `ICFetchResponseParserTest` (Instance and Class Methods), `ICHelperTest` (Instance and Class methods)

**Comment by EightSQ** [comment]
Has been solved with #233.
