### ISSUE TITLE
ICAuthenricationInfo>>isValid misleading name?

### ISSUE THREAD

**Issue by querenker** [hpi-swa-teaching/IMAPClient#21]
The message checks if the username and passwort differs from the default values.
If the default values are not valid values, the name default value is a little bit misleading?

Furthermore if a server has these default values as user credentials, they can not be used, because they are incorrectly recognised as "inValid".

In my opinion these message is not necessary and can be deleted

**Comment by julianweise** [comment]
We renamed default\* to initial*.
Those constants only contain empty Strings which should never interfere with any server credentials.
