### ISSUE TITLE
Remove FileIO, store data inside image

### ISSUE THREAD

**Issue by Paulpanther** [hpi-swa-teaching/IMAPClient#212]
also fixes #192, #227.

**Comment by Paulpanther** [comment]
#192 Will be fixed by this issue too

**Comment by Paulpanther** [comment]
Still open, since emails still get stored in fileIO

**Comment by JuliaJoch** [comment]
A stakeholder mentioned there is a good reason for FileIO. Emails can be seen as documents which you want to be saved persistently on your disc (e.g. invoices, bills, ...). Therefore we keep the fileIO possibility.
We are refactoring it in a way that puts it into a single class though in order not to pollute the main Classes with half ready functionality.
 For synchronization with MailDir Files on Disk the filenames have to be changed (the uniqueID of a mail is not the correct MailDir filename). Thsi will be a lot of work to properly synchronize! Therefore we delay this issue into a new one for possible enhancement and close the discussion for now. #348
