### ISSUE TITLE
Inconform Error to UI Note

### ISSUE THREAD

**Issue by Paulpanther** [hpi-swa-teaching/IMAPClient#229]
The error for inconform info should look like the other errors in the IMAP UI

**Comment by EightSQ** [comment]
@Paulpanther Could you please specify what exactly you mean with _inconform info_? Have I already addressed this with 1a09982?

**Comment by timgarrels** [comment]
@Paulpanther

**Comment by felixrindt** [comment]
Putting in an invalid character. e.g. `\` in the password fields does not create a Note, but a hard exception:

![image](https://user-images.githubusercontent.com/5970076/61892089-5bbb1880-af0b-11e9-8678-ac2579201b4d.png)

**Comment by felixrindt** [comment]
Should rather be a note like the other errors
![image](https://user-images.githubusercontent.com/5970076/61892133-6fff1580-af0b-11e9-91b2-b7db87e16243.png)
