### ISSUE TITLE
Remove comments in source code resp. using message comments

### ISSUE THREAD

**Issue by querenker** [hpi-swa-teaching/IMAPClient#23]
- [x] ICEndpoint>>connectTo: a "stream nextResponse" call is needed to skip the server greetings. Since this call is on a different abstraction level and the purpose is not clear a commend was used.
  Ideas:
  1.  a skipServerGreetings message which encapsulate this line
  2. a checkServerGreetings message which encapsulate this line and could (later) check the greeting for success etc.
- [x] ICEndpoint>>fetchNextResponse
  ideas:
  1. using the message comment 
- [x] ICEndpoint>>folderFromResponse
  idea:
  1. using the message comment

**Comment by julianweise** [comment]
How to add a method comment?

**Comment by querenker** [comment]
It is a simple comment directly under the message definition.
An (random) example copied from Squeak:

```
asDisplayText
    "Answer a DisplayText whose text string is the receiver."

    ^DisplayText text: self asText
```
