### ISSUE TITLE
Account delete causes Error

### ISSUE THREAD

**Issue by Paulpanther** [hpi-swa-teaching/IMAPClient#239]
This happens because the method `ICEndPoint removeConfiguration:`  receives an EndPoint, but expects an Dictionary

**Comment by timgarrels** [comment]
The expected dictionary is supposed to hold at least the following fields:
username, port, address, name, ssl

Each `ICEndpoint` holds `name` and `ssl`.
It also holds an `authenticationInfo` object, which itself holds a `username`.

It also holds an `serverInfo` object, which itself holds a `port and `host`. `host` is equal to the `address` here.
We could create a method which builds up the expected dictionary in endpoint.
