### ISSUE TITLE
Insert default later

### ISSUE THREAD

**Issue by Paulpanther** [hpi-swa-teaching/IMAPClient#265]
In `ICLoginDialog>>login`: The defaults are inserted before the validity checks. This causes the defaults to be inserted into the UI-TextFields if the checks aren't successful. If the defaults are inserted later this will not happen

**Comment by JuliaJoch** [comment]
Isn't this the expected behaviour? If we leave out the server port in the login dialog we insert the default visibly, so that we know that a default value was used.
