### ISSUE TITLE
Moving an email to trash makes it unseen again

### ISSUE THREAD

**Issue by EightSQ** [hpi-swa-teaching/IMAPClient#288]
The email should not change its flags being moved to trash.

**Comment by shm0sby** [comment]
I cannot reproduce that emails become **unseen** again. But the flag, that can be used with the context menu via `Mark as flagged` does indeed get removed.

Did you mean that?

**Comment by EightSQ** [comment]
Described in [RFC 3501](https://tools.ietf.org/html/rfc3501#section-2.3.2) is that the `\Flagged` and the `\Seen` flags in theory are both system flags. Since this was way at the end of the semester last year, I  think we did not look further into this, however we were able to observe this behaviour.

Back then, *unseen mails* were shown as bold-font list entries.
