### ISSUE TITLE
#isDigit sent to `nil`

### ISSUE THREAD

**Issue by fniephaus** [hpi-swa-teaching/IMAPClient#309]
After clicking the `Update` button, I get the following error:

![image](https://user-images.githubusercontent.com/2368856/81149110-de363580-8f7d-11ea-9dfa-2eb16404c8b9.png)

**Comment by fniephaus** [comment]
`ICEmail>>#dateInSecondsSince1980` sends `self date`, but the result can be an empty string. This seems to be the problem.

**Comment by shm0sby** [comment]
This error comes from MS Exchange objects which aren't emails.
Could be either a calendar entry or a contact etc. 
We might exclude them explicitly or ignore them somehow if the entries do not have a date.

An idea would be to remove all e-mails without a date from the email collection inside of
`ICFolder>>addMails` to ignore Exchange specific elements.

Regarding to https://tools.ietf.org/html/rfc2822#section-3.6 we can simply assume that all e-mails have a date.

**Comment by shm0sby** [comment]
Fixed with last commit.

**Comment by fniephaus** [comment]
Thank you!
