### ISSUE TITLE
Consider giving the ICMail a reference to the ICEndpoint

### ISSUE THREAD

**Issue by JuliaJoch** [hpi-swa-teaching/IMAPClient#368]
The ICFolder is responsible for all actions offered in the ICFolder Dialog. The ICEmail is responsible for the ICEmailDialog. Therefore the ICEmail is responsible for retrieving its own body. In order to do that it needs to access the endpoint. It does this at the moment by getting the endpoint from its folder, which is not according to the law of demeter. 

This is a good first issue to dive into our architecture and discuss with your team whether you want to refactor it further.

**Comment by laugengebaeck** [comment]
As far as I'm aware, the ICFolder now does everything related to this. Therefore not relevant anymore.
