### ISSUE TITLE
Cannot view image attachments

### ISSUE THREAD

**Issue by LinqLover** [hpi-swa-teaching/IMAPClient#393]
**Steps to reproduce:**

1. Click on an attachment in a message
2. Choose "view this image attachment"

**Expected result:**
The picture is opened in the image.

**Actual result:**
DNU error for `#viewBody` in `TextMessageLink>>#actOnClickFor:`.

**Notes**

Looks like this could be an upstream bug in the Trunk. If you can confirm this, it should not be so complicated to contribute a fix back to the Trunk, see <https://squeak.org/development_process/>.

**Comment by antonneubauer** [comment]
images are openable since commit 5c93c4f - on branch us18-open-image-attachments, to be merched into develop
