### ISSUE TITLE
connection clearing when closing squeak

### ISSUE THREAD

**Issue by christian-helms** [hpi-swa-teaching/IMAPClient#397]
As a user I don't want get an error message when I open the IMAP-Client after it has been closed due to a shutdown of Squeak. This is important to me since I don't want to pay attention to closing the IMAP-Client before I close Squeak.​

Acceptance criteria:​

- Every time I start the IMAP-Client only the login window appears.​

- When Squeak wants to shut itself down the IMAP-Client is informed to clear the connection.

**Comment by laugengebaeck** [comment]
Idea: `Smalltalk addToShutDownList: self` together with a `shutDown: isGoingDown` method for the `ICFolderDialog` should solve this (see [Seaside documentation](http://book.seaside.st/book/advanced/persistency/image-based-persistency))
