### ISSUE TITLE
deleting emails may change messageIDs stored in Email object

### ISSUE THREAD

**Issue by querenker** [hpi-swa-teaching/IMAPClient#40]
Currently a dynamic message id is stored in an email object. The message ids are enumerated beginning from 1 on the server. If a email is removed out of our system from the server, the stored message ids may not be up to date.
This could be fixed by a server wide global message id or by fetching the message ids every time before they are used.

**Comment by davidhennemann** [comment]
Closed because we use UIDs at the moment
