### ISSUE TITLE
Test refactoring

### ISSUE THREAD

**Issue by querenker** [hpi-swa-teaching/IMAPClient#7]
TestCase method not used properly

for example:
`[self assert: (self endPoint ping)]
        on: Exception 
        do: [ ^ self ].
    self fail`
`self should: (self endPoint ping) raise: Exception`

`self assert: (self endPoint logout) = true.`
`self assert: (self endPoint logout) equals: true`
or even better: `self assert: (self endPoint logout).`

**Comment by julianweise** [comment]
refactored all tests.
