### ISSUE TITLE
Improve the Save Credentials Feature

### ISSUE THREAD

**Issue by davidhennemann** [hpi-swa-teaching/IMAPClient#76]
A User who checks his mails on a regular basis, wont fill in his credentials every time. So I implemented the save credentials check box. Its just creating an config.txt in the Resources Directory, where the credentials are stored in plaintext. This is far away from being good. If i hand my squeak image to a friend, i would also give him my password in plain text. 

- We shouldnt save the Logindata file into the resource directory of the image
- We should encrypt it somehow. The IMAP Client should be the only one able to decrypt it again. But how should we implement this? Any Ideas?

**Comment by mariwalt** [comment]
Maybe we should also store and load the setting for "Use SSL".

**Comment by davidhennemann** [comment]
Good idea! Will implenent later :)
