### ISSUE TITLE
Tests call other tests

### ISSUE THREAD

**Issue by querenker** [hpi-swa-teaching/IMAPClient#8]
testLogout_EverythingFine calls testConnectToOnAndLoginUsing_EverythingFine

**Comment by julianweise** [comment]
Vermeidet Codeduplikation.
Zum Testen der Logout-Funktionalitäten muss natürlich die Client eingeloggt sein.
Natürlich wird der Login dann zweimal ausgeführt (über alle Tests gesehen), aber ist das so schlimm?

**Comment by querenker** [comment]
Ich glaube am einfachsten ist es, wenn wir das morgen früh bei unserem Treffen besprechen. Die Issues waren auch erstmal eher dazu gedacht, dass wir uns bis morgen noch daran erinnern können :) (wir sollten uns auch generell überlegen, welche Sprache wir für Issues etc. nutzen)

**Comment by julianweise** [comment]
We should discuss this tomorrow and close this issue soon.
