### ISSUE TITLE
Feature: Delete emails

### ISSUE THREAD

**Issue by mariwalt** [hpi-swa-teaching/IMAPClient#81]
Deleting messages in IMAP is a bit tricky, as there is no explicit delete command. Instead, a flag is set on the message marking it as deleted. This, by itself, does nothing to get the message removed. Just when a special command is called all messages in the current folder marked as to be deleted are removed.

. UID SEARCH ALL
* 1 EXISTS
* 1 RECENT
* SEARCH 1814
. OK Completed
. UID STORE 1814 +FLAGS (\Deleted)
* 1 FETCH (FLAGS (\Recent \Deleted \Seen) UID 1814)
. OK Completed
. EXPUNGE
* 1 EXPUNGE
* 0 EXISTS
* 0 RECENT
. OK Completed
. UID SEARCH ALL
* SEARCH
. OK Completed

The above is executed in a folder containing just a single message (see the result of the UID SEARCH ALL). The flag \Deleted is then added to flag list of the message (UID STORE 1814 +FLAGS (\Deleted)). The STORE command returns the new flag list. The EXPUNGE command then removes the message.

**Comment by davidhennemann** [comment]
Whats your progress with this? This issue is in a milestone, which is overdue since 8 days. And i think that there will be a lot of merge conflicts, because the develop-branch is a lot of commits ahead now.

**Comment by mariwalt** [comment]
This issue can be closed, since the pull request for this issue was already merged on Jun 2, 2018 and the feature works fine on the current develop branch.
