### ISSUE TITLE
Make it possible to add multiple user accounts

### ISSUE THREAD

**Issue by ClayGee** [hpi-swa-teaching/IMAPClient#97]
- [x] add PluggbleListSpec to IMAP Overview window with current user account
- [x] add button to add an account
- [x] find out how to find the email domain "student.hpi.de" because currently only the user name "claudia.grabowski" is displayed
- [x] create a login window for that purpose (or reuse the existing one somehow)
- [x] after entering the login information, display the email account in the List
- [x] make it so when you click on a different account the correct folderstructure gets displayed

**Comment by davidhennemann** [comment]
sounds great 😍
